### PR TITLE
#31 ft: add header component

### LINKED ISSUE #31: Header

### PR DESCRIPTION
**Pull request by shyakadavis**
# Description
This P.R delivers

- The header component
- Theme toggling use system preference and manual options
- sub header with a collapsable sidebar.

### 🔗 Links
📸 [Loom](https://www.loom.com/share/4ef48c45560d4f7ca0cb3c9f25e543b6)

📚[Storybook](https://642be4392be27ccecd364aa0-mqdlmbqbto.chromatic.com)

Fixes #31 

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by musllim — DISMISSED** [review]
Are using plain css?

**Comment by shyakadavis** [comment]
> https://deploy-preview-33--beamish-peony-17341f.netlify.app

Sorry for the late reply, but to answer, no. I am using tailwind.

**Comment by shyakadavis** [comment]
> Are using plain css?

Sorry for the late reply, but no. I am using tailwind.

**Review by SergeInGithub — COMMENTED** [review]
Spectacular @shyakadavis, 
but looking at storybook, the standard menu bar is kind of behind the navbar and the upper letters are sort of hidden. e.g: ```All``` ```Today's Deals```, etc... those words are cut off on the top and you can't clearly see them. if you can find a way to pull the menu bar just a little i think it'd work

**Comment by shyakadavis** [comment]
> Spectacular @shyakadavis, but looking at storybook, the standard menu bar is kind of behind the navbar and the upper letters are sort of hidden. e.g: `All` `Today's Deals`, etc... those words are cut off on the top and you can't clearly see them. if you can find a way to pull the menu bar just a little i think it'd work

Same issue addressed in the loom video.
Since I used fixed positions for Navbar and SubHeader, it affected presentation in storybook, but works just fine in the app.

**Pull request closed without merging**
