### PR TITLE
ft-login#184749813

### PR DESCRIPTION
**Pull request by emilenfc**
# Description

This is the implementation of login feature

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by SergeInGithub — COMMENTED** [review]
This is good @emilenfc, but once someone successfully logs-in you actually need to keep the token in the `localStorage` and in the `store` as well because we need to use it to authorize other routes ASAP❗

**Review by musllim — APPROVED** [review]
LGTM

**Review by SergeInGithub — APPROVED** [review]
LGTM

**Review by shyakadavis — APPROVED** [review]
LGTM

**Review by SergeInGithub — APPROVED** [review]

**Review by ISHIMWE-Aime — APPROVED** [review]
LGTM

**Pull request merged**
