### PR TITLE
ft: add cart summary card component

### PR DESCRIPTION
**Pull request by SergeInGithub**
# Description

This will add the following components:
- Cart summary card component

This will show up besides the besides the cart items and it will show a summary of items in the cart as well as their total cost

📹   Loom video link: https://www.loom.com/share/37abc101fbe54bb19615842570099f5f

Fixes # (#22)

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature or Enhancement (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have created a loom video for the new feature or enhancement
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by musllim — DISMISSED** [review]
Looks good

**Review by shyakadavis — COMMENTED** [review]
Awesome 🚀 

Notes:

- The items being rendered are actually just one string. I think they should be an array to map because a user can have many items on their cart, and rendering just one won't do.
Speaking of which, what are you trying to do here? Aren't trying to render a calculated sum of the total of the items in the cart? If so, `items` should be a number resulting from a calculated sum of the mapped cart items.
- Have you tried looking at this on a small screen size? It looks off.
- The border radius around the `buyer protection` seems abused and is not contributing but taking away from the look. Try removing the `bg`, and leave just a coloured notice.

**Review by musllim — APPROVED** [review]
LGTM

**Review by shyakadavis — APPROVED** [review]
LGTM

**Review by musllim — DISMISSED** [review]
LGTM

**Review by shyakadavis — APPROVED** [review]
LGTM

**Review by musllim — APPROVED** [review]
LGTM

**Review by ISHIMWE-Aime — APPROVED** [review]
LGTM

**Review by emilenfc — APPROVED** [review]
LGTM

**Review by mucyoalexaxel — APPROVED** [review]
LGTM

**Pull request merged**
